service: infracreation
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: us-east-2
  deploymentPrefix: infracreation

resources:
  - ${file(./resources/ec2.yml)}
  - ${file(./resources/ssmParameters.yml)}
