---
Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Email
      Type: String
      Value: supreetreddy99@gmail.com
      Description: SSM Parameter for running date command.

  BasicParameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: phoneNumber
      Type: String
      Value: 08888888888
      Description: SSM Parameter for running date command.

  BasicParameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: universityName
      Type: String
      Value: illinois university
      Description: SSM Parameter for running date command.

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: vpc-0b0c96f49a173b496
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
